### PR TITLE
Fix fallout from https://github.com/opentracing/basictracer-go/pull/36

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by tamird** [comment]
Apparently this needs a rebuild without cache, since circle has cached the old version of basictracer-go.

**Comment by bensigelman** [comment]
Thank you!

(Insert rant about the state of vendoring for small packages in Go)

**Comment by tamird** [comment]
Indeed.

**Comment by bensigelman** [comment]
Blargh... I'm in an airplane using my phone and GH won't allow mobile browser merges when the tests are failing.

**Comment by tamird** [comment]
If you can get into circle CI and trigger a rebuild without cache you might be able to work around.

**Comment by bensigelman** [comment]
Spoofed my browser :)

Thanks again.

**Pull request merged**
