### PR TITLE
LS-1251 clean build

### PR DESCRIPTION
**Pull request by viruslobster**

### CODE REVIEW

**Comment by viruslobster** [comment]
I'll need help

**Comment by viruslobster** [comment]
The dockerfile for this is in github.com/lightstep/sandbox/mstevens/docker but I'm not sure how to host it

**Comment by jmacd** [comment]
Re: hosting, I forget exactly how to get docker-hub credentials around here. Ultimately you'll run "docker push" with the image you've built.

**Comment by jmacd** [comment]
(I have a feeling Spoons is the person who can invite you to docker hub's Lightstep organization, but you probably can go ahead and create a login on hub.docker.com.

**Pull request merged**
