### PR TITLE
Added new constructor for tracer that propagates error.

### PR DESCRIPTION
**Pull request by bwplotka**
Fixes https://github.com/lightstep/lightstep-tracer-go/issues/226

I also made error handling consistent for `NewTracer` - now it emits event only. 

Overall I would suggest totally removing the emit event logic. It is not the best idea to have a global logger, especially for the library: it might cause issues if someone wants some flexibility (e.g running two tracers with different loggers.). Anyway, not a blocker for us here (: 

Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by bwplotka** [comment]
Any ideas what's wrong with this test?

**Comment by iredelmeier** [comment]
Hi @bwplotka! The test problem seems to be unrelated to your change.

@codeboten just added #229, which should mitigate the timeout issue.

**Comment by codeboten** [comment]
Looks like we're occasionally bumping up against the default `go test` 10 minute timeout. Opened a PR (https://github.com/lightstep/lightstep-tracer-go/pull/229) to address by bumping the timeout for now. Mind rebasing and giving your branch another try once that PR is merged?

**Comment by antonio** [comment]
@iredelmeier @codeboten is there a timeline for a new release that includes this patch?

**Pull request merged**
