### PR TITLE
Avoid reflection with %T formatter

### PR DESCRIPTION
**Pull request by jmacd**

### CODE REVIEW

**Comment by jmacd** [comment]
Are we going to start a 0.16 branch?

**Comment by jmacd** [comment]
Should we use branches or master?

**Comment by MatthewDolan** [comment]
Um, I feel like we should cut another branch again (if no one has any objections). That process worked well and helped keep these changes off of master where they could be picked up with `go get`. I just named it whatever the version I expect it to be released under.

**Comment by jmacd** [comment]
I agree. I find working on a branch leads to more git mistakes. That's all.

**Pull request merged**
