### PR TITLE
Update gopsutil to v3.21.3

### PR DESCRIPTION
**Pull request by aashishkapur**
I'm getting the following warning when building a package depending on lightstep-tracer-go:
../../pkg/mod/github.com/shirou/gopsutil/v3@v3.21.2/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]

We can fix this by upgrading gopsutil, see https://github.com/shirou/gopsutil/pull/1042

### CODE REVIEW

**Comment by aashishkapur** [comment]
@codeboten - mind triggering CI for this branch? Looks like I don't have permissions

**Comment by aashishkapur** [comment]
@codeboten friendly bump on this PR!

**Comment by codeboten** [comment]
re-opening to trigger circle ci. not sure why the status didnt report here.

**Comment by aashishkapur** [comment]
Looks like that did it - thanks! Is there anything I can do to get this merged in?

**Comment by aashishkapur** [comment]
Could I get your review on this PR @codeboten?

**Review by codeboten — APPROVED** [review]
Thanks for the update!

**Pull request merged**
